#!/bin/bash
# ============================================================================
# AutoMatrix ERP - Deployment Script
# ============================================================================
# Combines all modular .gs files into a single script.gs for Apps Script
# ============================================================================

set -e  # Exit on error

echo "🚀 AutoMatrix ERP Deployment Script"
echo "===================================="
echo ""

# Configuration
OUTPUT_FILE="script.gs"
BACKUP_DIR="backups"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

# Create backup directory if it doesn't exist
mkdir -p "$BACKUP_DIR"

# Backup existing script.gs if it exists
if [ -f "$OUTPUT_FILE" ]; then
    echo "📦 Backing up existing script.gs..."
    cp "$OUTPUT_FILE" "$BACKUP_DIR/script_${TIMESTAMP}.gs"
    echo "   ✅ Backup saved to $BACKUP_DIR/script_${TIMESTAMP}.gs"
fi

echo ""
echo "🔨 Building deployment package..."
echo ""

# Create header
cat > "$OUTPUT_FILE" << 'EOF'
// ============================================================================
// AUTOMATRIX ERP - MODULAR BUILD
// ============================================================================
// This file is auto-generated by deploy.sh
// DO NOT EDIT MANUALLY - Edit source files in src/server/ instead
// ============================================================================
// Build Date: 
EOF

# Add build timestamp
echo "// Generated: $(date)" >> "$OUTPUT_FILE"
echo "//" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Function to add file with header
add_file() {
    local file=$1
    local name=$(basename "$file")
    
    if [ -f "$file" ]; then
        echo "   ✅ Adding $name"
        echo "" >> "$OUTPUT_FILE"
        echo "// ============================================================================" >> "$OUTPUT_FILE"
        echo "// SOURCE: $file" >> "$OUTPUT_FILE"
        echo "// ============================================================================" >> "$OUTPUT_FILE"
        cat "$file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    else
        echo "   ⚠️  File not found: $file (skipping)"
    fi
}

# Add files in dependency order
echo "📋 Layer 1: Configuration"
add_file "src/server/config/constants.gs"
add_file "src/server/config/schema.gs"
add_file "src/server/config/permissions.gs"

echo ""
echo "📋 Layer 2: Utilities"
add_file "src/server/utils/date.gs"
add_file "src/server/utils/formatting.gs"
add_file "src/server/utils/sheets.gs"

echo ""
echo "📋 Layer 3: Core Modules"
add_file "src/server/core/locks.gs"
add_file "src/server/core/auth.gs"
add_file "src/server/core/validation.gs"
add_file "src/server/core/audit.gs"

echo ""
echo "📋 Layer 4: Business Modules"
# Add business modules (will be created in future iterations)
if [ -d "src/server/modules" ]; then
    for file in src/server/modules/*.gs; do
        if [ -f "$file" ]; then
            add_file "$file"
        fi
    done
else
    echo "   ℹ️  No business modules found yet"
fi

echo ""
echo "📋 Layer 5: Main Entry Point"
add_file "src/server/main.gs"

echo ""
echo "✅ Build complete!"
echo ""
echo "📊 Statistics:"
echo "   Output file: $OUTPUT_FILE"
echo "   File size: $(wc -c < "$OUTPUT_FILE") bytes"
echo "   Lines of code: $(wc -l < "$OUTPUT_FILE") lines"
echo ""

# Validate the output
if grep -q "function doGet" "$OUTPUT_FILE"; then
    echo "✅ Validation passed: doGet() function found"
else
    echo "⚠️  Warning: doGet() function not found - deployment may fail"
fi

echo ""
echo "📝 Next Steps:"
echo "   1. Open your Google Apps Script project"
echo "   2. Replace the content of script.gs with the generated file"
echo "   3. Copy Index.html from src/client/Index.html"
echo "   4. Deploy as web app"
echo ""
echo "🎉 Deployment package ready!"
